config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  get '/logout', to: "sessions#destroy"
  get '/register', to: "users#new"

  resources :posts, except: [:destroy] do
    member do
      post 'vote'
    end

    resources :comments, only: [:create] do
      member do
        post 'vote'
      end
    end
  end
  resources :categories, except: [:destroy]
  resources :users, only: [:show, :create, :edit, :update]

end

app/models/category.rb
class Category < ActiveRecord::Base
  include Slugable

  has_many :post_categories
  has_many :posts, through: :post_categories
  validates :name, presence: true


  slugable_column :name



end

app/models/comment.rb
class Comment < ActiveRecord::Base
  include Voteable

  belongs_to :user
  belongs_to :post

  validates :body, presence: true


  
end

app/models/post.rb
class Post < ActiveRecord::Base
  include Voteable
  include Slugable


  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  has_many :comments
  has_many :post_categories 
  has_many :categories, through: :post_categories


  
  validates :title, :url, presence: true
  validates :title, length: {minimum: 2, maximum: 140}
  validates :description, length: {maximum: 1000}
  validates :url, length: {minimum: 2}

  slugable_column :title


end

app/models/post_category.rb
class PostCategory < ActiveRecord::Base
  belongs_to :post
  belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
  include Slugable
  has_many :posts
  has_many :comments
  has_many :votes

  has_secure_password validations: false

  validates :username, presence: true, uniqueness: true

  validates :password, presence: true, on: :create, length: {minimum: 5}

  slugable_column :username

  def admin?
    self.role == "admin"
  end

  def moderator?
    self.role == "moderator"
  end


end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :creator, class_name: "User", foreign_key: "user_id"
  belongs_to :voteable, polymorphic: true

  validates_uniqueness_of :creator, scope: [:voteable_id, :voteable_type]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    unless logged_in?
      flash[:error] = "Please log in"
      redirect_to login_path

    end
  end

  def require_admin
    access_denied unless logged_in? && current_user.admin?
  end

  def access_denied
      flash[:error] = "You can't do that"
      redirect_to root_path
  end


end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_user, only: [:new, :create]
  before_action :require_admin, only: [:new, :create]

  def index 
    @categories = Category.all
  end

  def show 
    @category = Category.find_by slug: params[:id]
    @posts = @category.posts
  end


  def new
    @category = Category.new
  end

  def create
    @category = Category.new(post_params)
    if @category.save
      redirect_to categories_path
    else
      render :new
    end
  
  end


  def post_params
      params.require(:category).permit!
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController 

  before_action :logged_in?, only: [:vote]


  def show
    @comment = Comment.find(params[:id])
  end

  def create
    @user = User.find(session[:user_id]) ## Need to change this later
    @post = Post.find_by slug: (params[:post_id])
    @comment = @post.comments.build(params.require(:comment).permit!)
    @comment.user = @user

    if @comment.save 
      redirect_to post_path(@post) 
    else
      render "posts/show"
    end
  end

  def vote


    @comment = Comment.find(params[:id])
    @vote = Vote.create(voteable: @comment, creator: current_user, vote: params[:vote])
    
    respond_to do |format|
      format.html do

        if @vote.valid?
          flash[:notice] = "Your vote was counted."
        else
          flash[:error] = "You can only vote once"
        end
        redirect_to :back
      end
      format.js
    end



  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :set_post, only: [:show, :edit, :update, :vote]
  before_action :logged_in?, except: [:index, :show]
  before_action :require_user, except: [:index, :show]
  before_action :require_creator, only: [:edit, :update]
  
  def index
    @posts = Post.all.sort_by{|x| x.total_votes}.reverse
  end

  def show
    @comment = Comment.new
    @comments = @post.comments
  end

  def new
    redirect_to root_path unless logged_in?
    @post = Post.new    
  end

  def create
    @post = Post.new(post_params)
    @post.creator = current_user
    if @post.save
      redirect_to posts_path
    else
      render :new
    end
  end

  def edit
  end 

  def update
    if @post.update(post_params)
      flash[:notice] = "Post updated"
      redirect_to posts_path
    else
      render :edit
    end
  end

  def vote
    @vote = Vote.create(voteable: @post, creator: current_user, vote: params[:vote])

    respond_to do |format|
      format.html do
        if @vote.valid?
          flash[:notice] = "Your vote was counted."
        else
          flash[:error] = "You can only vote once"
        end
          redirect_to :back
      end
      format.js
    end
  end



  private

  def post_params
    params.require(:post).permit!
  end

  def set_post
    @post = Post.find_by(slug: params[:id])
  end

  def require_creator
    access_denied unless logged_in? && (current_user == @post.creator || current_user.admin?)
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    if logged_in? 
      flash[:error] = "You are already logged in"
      redirect_to root_path
    end
  end

  def create
    user = User.where(username: params[:username]).first
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:notice] = "Welcome, you've logged in."
      redirect_to root_path
    else
      flash[:error] = "There is something wrong"
      redirect_to login_path

    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You've logged out."
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:notice] = "You are registered"
      redirect_to root_path
    else
      render :new
    end
  end

  def show
     @user = User.find_by slug: params[:id]
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def fix_post_url (url)
    if url.start_with?("www.")
      "http://#{url}"
    elsif url.start_with?("http://")
      url
    else
      "http://www.#{url}"
    end
  end

  def display_datetime(dt)
    dt.strftime("%m/%d/%Y %l:%M%P %Z")
    
  end


end

app/views/categories/_category.html.erb
<%= link_to category_path(category.slug) do %>

<span class="badge"><%= category.name %></span>

<% end %>

app/views/categories/index.html.erb
<% if logged_in? && current_user.admin?%>

  <%= link_to new_category_path do  %>
  <div class="btn btn-success">Add Category</div>
  <% end %>
  <br>
  <br>
  <br>

<% end %>


<% @categories.each do |category| %>
  <%= link_to category.name, category_path(category) %>
  <br>

<% end %>

app/views/categories/new.html.erb
<h1> New Category </h1>

<%= render "shared/errors", object: @category %>


<%= form_for @category do |f| %>

<%= f.label :name, "Category name" %><br>
<%= f.text_field :name %>
<br>
<%= f.submit "Submit new Category" %>

<% end %>

app/views/categories/show.html.erb
<%= render 'shared/content_title', title: @category.name %>

<%= render @posts %>

app/views/comments/_comment.html.erb
<% show_post ||= false %>



<div class="row">
  <div class='span0 well text-center'>
    
    <% if logged_in? %>
      <%= link_to vote_post_comment_path(comment.post, comment, vote: true), method: 'post', remote: true do %>
        <i class="icon-arrow-up"></i>
      <% end %>
    <% end %>
    <br>
    <span id="comment_<%= comment.id%>_votes"><%= comment.total_votes %> votes</span>
    <br>

    <% if logged_in? %>
      <%= link_to vote_post_comment_path(comment.post, comment, vote: false), method: 'post', remote: true do %>
        <i class="icon-arrow-down"></i>
      <% end %>
    <% end %>

  </div>

  <div class="well span8">
    <%= comment.body %>
    <p class="quiet"> by <%= comment.user.username %> </p>
  </div>
</div> <!-- .row -->

app/views/comments/_comments.html.erb
<% show_post ||= false %>

<% @comments.each do |comment| %>

<%= comment.body %>
<p class="quiet"> by <%= comment.user.username %> </p>

<% end %>

app/views/comments/show.html.erb
<%= render 'comment' %>

app/views/comments/vote.js.erb
<% if @vote.valid? %>
  $("#comment_<%= @comment.id %>_votes").html("<%= @comment.total_votes%> votes");
<% else %>
  alert("You can only vote on a comment once.");
<% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == "notice" ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav">
  <li>
    <%= link_to "Postit!", root_path, :class => 'brand' %>
  </li>
  <% if logged_in? %>
  <li>
    <%= link_to 'New Post', new_post_path %>
  </li>
  <% end %>
   <li>
    <%= link_to 'Categories', categories_path %>
  </li>

<% if logged_in? %>
  <li>
    <%= link_to 'Log out', logout_path %>
  </li>

  <% else %>
  <li>
    <%= link_to "Log in", login_path %>
  </li>

  <li>
  <%= link_to "Register", register_path %>
  </li>

<% end %>



</ul>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tealeaf Academy - Postit</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header>
      <div class="navbar">
        <div class="navbar-inner">
          <div class="container">
            <%= render 'layouts/navigation' %>
          </div>
        </div>
      </div>
    </header>
    <div id="main" role="main">
      <div class="container">
         <div class="row">
          <div class="span12">
            <%= render 'layouts/messages' %>
            <%= yield %>
          </div>
        </div>
        <footer>
        </footer>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/posts/_form.erb
<%= render "shared/errors", object: @post %>

<%= form_for @post do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br>

  <%= f.label :url %>
  <%= f.text_field :url %>
  <br>

  <%= f.label :description %>
  <%= f.text_field :description %>
  <br>
  
  <%= f.label "Categories" %>
  <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
  <% cb.label(class: "checkbox inline") {cb.check_box(class: "checkbox") + cb.text} %>
  <% end %>
  <br>
  <%= f.submit(@post.new_record? ? "Create Post" : "Update Post") %>

<% end %>

app/views/posts/_form.html.erb
<%= render "shared/errors", object: @post %>

<%= form_for @post do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br>

  <%= f.label :url %>
  <%= f.text_field :url %>
  <br>

  <%= f.label :description %>
  <%= f.text_field :description %>
  <br>
  
  <%= f.label "Categories" %>
  <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
  <% cb.label(class: "checkbox inline") {cb.check_box(class: "checkbox") + cb.text} %>
  <% end %>
  <br>
  <%= f.submit(@post.new_record? ? "Create Post" : "Update Post") %>

<% end %>

app/views/posts/_post.html.erb
<div class="span0 well text-center">

    <% if logged_in? %>
      <%= link_to vote_post_path(post, vote: true), method: 'post', remote: true do %>
      <i class="icon-arrow-up"></i>
      <% end %>
    <% end %> 
    <br>
    <span id="post_<%=post.slug%>_votes"><%= post.total_votes %> votes</span>
    <br>

    <% if logged_in? %>
      <%= link_to vote_post_path(post, vote: false), method: 'post', remote: true do %>
    <i class="icon-arrow-down"></i>
    <% end %>
    <% end %>
  </div>


  <div class="row">
    <div class='span8 well'>
    <%= render post.categories %>
    <h4> <%= link_to post.title, fix_post_url(post.url) %></h4>
    <p> <%= post.description %> </p>
    <p>
      <span class='quiet'>posted by </span> <%= post.creator.username %> 
      <small>at <%= display_datetime(post.created_at)%></small>
    </p>
    <span>
      <%= link_to("#{post.comments.size} comments", post_path(post)) %>
      <% if logged_in? && current_user.username == post.creator.username %>
        <p><%= link_to "edit", edit_post_path(post) %></p>
      <% end %>
    </span>
    </div>
  </div>

app/views/posts/_posts.html.erb
<% @posts.each do |post| %>
<div class="span0 well text-center">

    <% if logged_in? %>
      <%= link_to vote_post_path(post, vote: true), method: 'post' do %>
      <i class="icon-arrow-up"></i>
      <% end %>
    <% end %> 
    <br>
    <%= post.total_votes %> votes
    <br>

    <% if logged_in? %>
      <%= link_to vote_post_path(post, vote: false), method: 'post' do %>
    <i class="icon-arrow-down"></i>
    <% end %>
    <% end %>
  </div>


  <div class="row">
    <div class='span8 well'>
    <%= render post.categories %>
    <h4> <%= link_to post.title, fix_post_url(post.url) %></h4>
    <p> <%= post.description %> </p>
    <p>
      <span class='quiet'>posted by </span> <%= post.creator.username %> 
      <small>at <%= display_datetime(post.created_at)%></small>
    </p>
    <span>
      <%= link_to("#{post.comments.size} comments", post_path(post)) %>
      <% if logged_in? && current_user.username == post.creator.username %>
        <p><%= link_to "edit", edit_post_path(post) %></p>
      <% end %>
    </span>
    </div>
  </div>
  <% end %>

app/views/posts/edit.html.erb
<h1> Edit </h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<%= render 'shared/content_title', title: "All Posts" %>

<%= render @posts %>

app/views/posts/new.html.erb
<h2> New post </h2>

Title

Url

Description

app/views/posts/show.html.erb
  <%= render @post.categories %>
</p>

<%= render 'shared/content_title', title: @post.title %>

<div class='light-gray-background'>
  <%= @post.description %>
</div><br>

<% if logged_in? && @post.creator.username == current_user.username %>
  <%= link_to "Edit", edit_post_path(@post) %>
<br>
<% end %>

<hr>

<% if logged_in? %>
  <%= form_for [@post, @comment] do |f| %>
    <%= f.label :body %>
    <%= f.text_area :body %>
    <br>
    <%= f.submit "Add Comment" %>

  <% end %>
<% end %>
<br>
<br>
<br>
<br>



<%= render @comments %>

<hr>

app/views/posts/vote.js.erb
<% if @vote.valid? %>
  $("#post_<%=@post.slug%>_votes").html("<%= @post.total_votes%> votes");
  <% else %>
  alert("You can only vote on a post once");
  <% end %>

app/views/shared/_content_title.html.erb
<p class="lead">
  <%= title %>
  <hr>
</p>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div class="alert">
    <% object.errors.full_messages.each do |message|%>
      <li><p><%= message %></p></li>
    <% end %>
  </div>
<% end %>

app/views/users/new.html.erb
<h2> Register for a new account! </h2>

<%= form_for @user do |f| %>
<%= render '/shared/errors', object: @user %>
<%= f.label :username, "Username" %>
<%= f.text_field :username %>

<%= f.label :password, "Password" %>
<%= f.password_field :password %>
<br>
<%= f.submit "Register" %>



<% end %>

app/views/users/show.html.erb
<%= @user.username %> 's profile


<% if @user.created_at %>
  <p>User since <%= display_datetime(@user.created_at) %></p>

<% end %>
<br>

<h2> All posts </h2>

<% @user.posts.each do |post| %>

 <p><%= link_to post.title, post_path(post) %></p>
  
<% end %>